import type { NextPage } from 'next'
import Head from 'next/head'
import { Home } from '@/components'
import { dehydrate, QueryClient } from '@tanstack/react-query'
import {
  GET_ARTICLES_KEY,
  getArticles,
  defaultArticlesLimit,
} from '@/hooks/queries/useGetArticles'

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </>
  )
}

export async function getServerSideProps() {
  const queryClient = new QueryClient()

  await queryClient.prefetchInfiniteQuery([GET_ARTICLES_KEY], () =>
    getArticles(defaultArticlesLimit)
  )

  return {
    props: {
      dehydratedState: JSON.parse(JSON.stringify(dehydrate(queryClient))),
    },
  }
}

export default HomePage
