import type { NextPage } from 'next'
import Head from 'next/head'
import { Dropdown, DropdownItem } from '@components/Dropdown'
import ProfileName from '@components/ProfileName'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dropdown trigger={<ProfileName size={4} name="Joao Oliveira" />}>
        <DropdownItem label="Profile" href="/profile" />
        <DropdownItem label="Sign out" href="/signout" />
      </Dropdown>
    </>
  )
}

export default Home
